makeSidebar <- function()
{
  sidebarPanel(
  radioButtons(inputId="whereGraph",label="Get a Graph",
               choices=c("From Disk","Generate"),selected="From Disk"),
  conditionalPanel(
      condition="input.whereGraph=='From Disk'",
		  p(paste("Select a graph to load.",
          "For loading files, only graphml formats have been tested.",
          "However, it should be able to process:",
          paste(paste(eval(formals(read.graph)$format),collapse=", "),
                '.',sep=''),
       "It can take a while to load larger graphs,",
       "particularly ones with lots of attributes.",
       "Zipped graphs (humans) do not seem to load correctly at this time.",
          collapse=" ")),
        fileInput(inputId="graphFile",label="File",accept="graphml")),
  conditionalPanel(
      condition="input.whereGraph=='Generate'",
		  wellPanel(
			  generateSidebar(),
		     conditionalPanel(
			     condition="input.genMethod=='Erdos Renyi'",
				  p("The Erdos-Renyi graph has each edge independently",
				    "chosen with probability p.")),
		     conditionalPanel(
			     condition="input.genMethod=='K Regular'",
				  p("A K-regular graph is a graph where every vertex",
				    "has degree k.")),
		     conditionalPanel(
			     condition="input.genMethod=='Ring'",
				  p("A ring graph is a cycle.")),
		     conditionalPanel(
			     condition="input.genMethod=='Complete'",
				  p("The complete graph is the graph containing all possible",
				  "edges.")),
		     conditionalPanel(
			     condition="input.genMethod=='Complete Bipartite'",
				  p("The complete bipartite graph is the bipartite graph",
				    "containing all possible",
				  "edges between the parts.")),
		     conditionalPanel(
			     condition="input.genMethod=='Random Bipartite'",
				  p("The random bipartite graph is the bipartite graph",
				    "containing each of the possible",
				  "edges between the parts independently with probability p.")),
		     conditionalPanel(
			     condition="input.genMethod=='Tree'",
				  p("Generate a regular tree.")),
		     conditionalPanel(
			     condition="input.genMethod=='Stochastic Block Model'",
				  p("The stochastic block model has the vertices grouped,",
				    "with the edge probabilities defined by the kxk P",
					 "matrix. The probability of an edge between vertices",
					 "depends only on the groups they belong to. In this",
					 "implementation, the entries of P are uniform [0,1],",
					 "unless 'Diagonally Dominant' is chosen, in which case",
					 "the off-diagonals are U[0,0.5] and the diagonals are",
					 "U[0.5,1]. The blocks are of (roughly) equal size.")),
		     conditionalPanel(
			     condition="input.genMethod=='Forest Fire'",
				  p("At each time step an edge is added. This vertex is",
				    "'cited': connected to ambs vertices chosen uniformly",
					 "at random. For each cited vertex v:"),
				  p("1. We generate two random number, x and y, that are",
					 "geometrically distributed with means p/(1-p) and rp(1-rp).",
					 "(p is ‘fw.prob’, r is ‘bw.factor’.) The new vertex cites x",
					 "outgoing neighbors and y incoming neighbors of v, from those",
					 "which are not yet cited by the new vertex. If there are less",
					 "than x or y such vertices available then we cite all of",
					 "them."),
				 p("2. The same procedure is applied to all the newly cited",
					"vertices.")),
		     conditionalPanel(
			     condition="input.genMethod=='Kautz'",
				  p("From the 'igraph' help page:"),
     p("A Kautz graph is a labeled graph, vertices are labeled by strings",
     "of length ‘n+1’ above an alphabet with ‘m+1’ letters, with the",
     "restriction that every two consecutive letters in the string must",
     "be different. There is a directed edge from a vertex ‘v’ to",
     "another vertex ‘w’ if it is possible to transform the string of",
     "‘v’ into the string of ‘w’ by removing the first letter and",
     "appending a letter to it.")),
		     conditionalPanel(
			     condition="input.genMethod=='de Bruijn'",
				  p("From the 'igraph' help page:"),
     p("A de Bruijn graph represents relationships between strings. An",
     "alphabet of ‘m’ letters are used and strings of length ‘n’ are",
     "considered.  A vertex corresponds to every possible string and",
     "there is a directed edge from vertex ‘v’ to vertex ‘w’ if the",
     "string of ‘v’ can be transformed into the string of ‘w’ by",
     "removing its first letter and appending a letter to it."),
     p("Please note that the graph will have ‘m’ to the power ‘n’ vertices",
       "and even more edges, so probably you don't want to supply too big",
       "numbers for ‘m’ and ‘n’.")),
		     conditionalPanel(
			     condition="input.genMethod=='Aging Prefatt'",
				  p("Each time a new vertex is added it creates a number",
				    "of links to old vertices and the probability that an",
					 "old vertex is cited depends on its in-degree",
					 "(preferential attachment) and age.",
					 "The probability of connecting an old vertex to",
					 "the new one is proportional to:"),
				  p("(deg.coef k[i]^pa.exp +  zero.deg.appeal)(age.coef l[i]^aging.exp + zero.deg.appeal)"),
				  p("where k and l are the in degree and age. See the help page",
					 "for 'sample_pa_age' in the 'igraph' package")),
		     conditionalPanel(
			     condition="input.genMethod=='Growing Random Graph'",
				  p("At each time step a new vertex is added and m new",
				    "edges are added (uniformly at random if citation is FALSE,",
					 "otherwise from the new vertex to a uniformly chosen old",
					 "vertex.")
			  ),
		     conditionalPanel(
			     condition="input.genMethod=='Geometric Random Graph'",
				  p("First n points are generated uniformly on a square (or",
				    "torus). An edge is set between any pair of points of",
					 "distance at most radius. If 'Keep Coords' is true,",
					 "the coordinates are set as vertex attributes 'x' and",
					 "'y'.")),
		     conditionalPanel(
			     condition="input.genMethod=='Star'",
				  p("A star graph is a central vertex of degree n-1 and n-1",
				  "vertices of degree 1 connected to it.")),
		     conditionalPanel(
			     condition="input.genMethod=='Wheel'",
				  p("A star graph union a cycle.")),
		     conditionalPanel(
			     condition="input.genMethod=='Famous'",
				  p("A set of famous graphs appearing in the literature.",
				    "See the help page for 'make_graph' in the 'igraph'",
					 "package.")),
		     conditionalPanel(
			     condition="input.genMethod=='Atlas'",
				  p("A set of graphs appearing in the book 'An Atlas of Graphs',",
				    "Roland C. Read and Robin J. Wilson. This is all undirected",
					 "graphs with up to seven vertices. See the help page for",
					 "'graph_from_atlas' in the 'igraph'",
					 "package. The graph number '0' which is the empty graph",
					 "on zero vertices is not an option in this tool.")),
		     conditionalPanel(
			     condition="input.genMethod=='Watts Strogatz'",
				  p("A small world graph. A lattice is created with",
				    "dimension 'dim', number of vertices along each axis of",
					 "'size' and neighborhood width 'nei'. Then edges are",
					 "rewired with probability 'p'. Note this graph",
					 "is always undirected. Note that the number of vertices,",
					 "is size^dim, so be careful there.",
					 "While the approach can produce loops and multiple edges,",
					 "this implementation removes them, returning a simplified",
					 "version of the graph.")),
		     conditionalPanel(
			     condition="input.genMethod=='Barabasi'",
				  p("This is a stochastic algoritm that adds a vertex with",
				    "each discrete time step. The new vertex initiates m edges",
					 "to vertices with probability P[i]~d[i]^power+zero.appeal.",
				    "Here d[i] is the in-degree of vertex i")),
			  wellPanel(
				  p("Click the parameters button to adjust the parameters of",
					 "the model. Then click 'Generate' to generate the graph"),
				  generateParameters(),
				  actionButton(inputId='GenerateGraph',label="Generate")
			  ))),
  numericInput(inputId='seed',label="Random Number Seed",value=seed,
      min=1,max=100000,step=1),
            p("Clicking on `Plotting Parameters' opens/closes a menu of options for the plot."),
            plottingOpts(),
	 bsCollapse(
		 bsCollapsePanel("Save State",
           p(paste("Type in a base filename for the saved file.",
                   "This should be a pure root filename, no directory or",
                   "extensions.",
                   "If no filename is given, the default",
                   "is a file with a unique date/time in the name.")),
           textInput(inputId='outputfilename',label='Output Base Filename',
			           value=""),
               p(paste("The state file will be saved in the directory",
                       "set in your browser as the downloads directory",
                       "The file will be an RData file.")),
               downloadButton('downloadState','Download')),
                  id='downloadCollapse'),
	 bsCollapse(
		 bsCollapsePanel("Restore State",
               p(paste("Restoring the state restores all the variables",
                       "selected in the GUI with the exception of the",
                       "graph file.")),
              fileInput(inputId="saveFile",label="Restore File",
                        accept="RData")),id='uploadCollapse')

  )
}
